<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\api.service.alyoza.domain\api.service.alyoza.domain.csproj" />
    <ProjectReference Include="..\api.service.alyoza.infrastructure\api.service.alyoza.infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>

</Project>
